spring:
  main:
    banner-mode: "off"
  application:
    name: insurancechallenge-service
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_UPPER=false;
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: insurancechallenge-service
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
      percentiles: [0.5, 0.9, 0.95]

server:
  port: 5555
  servlet:
    context-path: /insurancechallenge/v1