spring:
  main:
    banner-mode: "off"
  application:
    name: insurancechallenge-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: insurancechallenge-service
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'

server:
  port: 5555
  servlet:
    context-path: /insurancechallenge/v1