{
 "title": "Métricas Aplicação",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume de chamadas por endpoint e status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/products\", method=\"POST\"}[1d])) by (uri, status)",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/products/{product_id}\", method=\"PUT\"}[1d])) by (method, status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Número de requisições endpoint POST",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{application=\"insurancechallenge-service\", uri=\"/products\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Número de requisições endpoint PUT",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{application=\"insurancechallenge-service\", uri=\"/products/{product_id}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latência Percentis - POST",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/products\"}[1d])) by (le)) * 1000",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\",uri=\"/products\"}[1d])) by (le)) * 1000",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\",uri=\"/products\"}[1d])) by (le)) * 1000",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Latência Percentis - PUT",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/products/{product_id}\"}[1d])) by (le)) * 1000",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\",uri=\"/products/{product_id}\"}[1d])) by (le)) * 1000",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\",uri=\"/products/{product_id}\"}[1d])) by (le)) * 1000",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Taxa de Requisições bem sucedidas",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(increase(http_server_requests_seconds_count{status=~\"2..\"}[1d])) by (application) + sum(increase(http_server_requests_seconds_count{status=~\"4..\"}[1d])) by (application)) / sum(increase(http_server_requests_seconds_count{}[1d])) by (application)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Taxa de Erro",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{status=~\"5..\"}[1d])) by (application) / sum(increase(http_server_requests_seconds_count{}[1d])) by (application)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resumo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"insurancechallenge-service\"}*1000"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"insurancechallenge-service\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{ application=\"insurancechallenge-service\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{ application=\"insurancechallenge-service\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_load_average_1m{ application=\"insurancechallenge-service\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{ application=\"insurancechallenge-service\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"insurancechallenge-service\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"insurancechallenge-service\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"insurancechallenge-service\",  area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"insurancechallenge-service\", area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "G1 Eden Space (heap)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 10, "x": 1, "y": 3 },
     "repeat": "memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{ application=\"insurancechallenge-service\", id=\"G1 Eden Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{ application=\"insurancechallenge-service\",  id=\"G1 Eden Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{ application=\"insurancechallenge-service\",  id=\"G1 Eden Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "G1 Old Gen",
     "type": "graph",
     "gridPos": { "h": 11, "w": 10, "x": 11, "y": 3 },
     "repeat": "memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{ application=\"insurancechallenge-service\", id=\"G1 Old Gen\", area=\"heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{ application=\"insurancechallenge-service\", id=\"G1 Old Gen\", area=\"heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{ application=\"insurancechallenge-service\", id=\"G1 Old Gen\", area=\"heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{ application=\"insurancechallenge-service\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{ application=\"insurancechallenge-service\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{ application=\"insurancechallenge-service\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{ application=\"insurancechallenge-service\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_active{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"}"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"} / hikaricp_connections_acquire_seconds_count{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"}",
       "legendFormat": "Acquire Time"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"} / hikaricp_connections_usage_seconds_count{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"}",
       "legendFormat": "Usage Time"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"} / hikaricp_connections_creation_seconds_count{ application=\"insurancechallenge-service\", pool=\"HikariPool-1\"}",
       "legendFormat": "Creation Time"
      }
     ]
    }
   ]
  }
 ]
}