scrape_configs:
  - job_name: 'app-scraper'
    metrics_path: '/insurancechallenge/v1/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5555']
        labels:
          application: 'insurancechallenge-service'
  
  - job_name: 'prometheus-listener'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']